### ISSUE TITLE
Property '$static' is missing in type

### ISSUE THREAD

**Issue by tuler** [eropple/fastify-openapi3#1]
```
Property '$static' is missing in type 'TObject<...>' but required in type 'TSchema'.ts(2345)
typebox.d.ts(77, 5): '$static' is declared here.
```

It looks like an incompatibility between TypeBox `0.23.5` (used by `fastify-openapi3`) and latest TypeBox `0.25.21`

**Comment by eropple** [comment]
Should be fixed with the update. I'll investigate `peerDependencies` when I can.
