### ISSUE TITLE
Typescript Error

### ISSUE THREAD

**Issue by ThalyssonLeite** [eropple/fastify-openapi3#2]
```
export const CounterSchema = schemaType('PingResponse', Type.Object({ pong: Type.Boolean() }))
```

This line generates the error: 
```
Argument of type 'TObject<{ pong: TBoolean; }>' is not assignable to parameter of type 'TSchema & CustomOptions'. Property '[Kind]' is missing in type 'TObject<{ pong: TBoolean; }>' but required in type 'TSchema'.ts(2345)
 ```
 
 It should be way more simple to get the things done don't you think?

**Comment by eropple** [comment]
Sorry, I missed this originally.

The error message is an unavoidable result of Typebox. TypeScript doesn't (and shouldn't) alias types deeply in error messages. It's just one of those things to deal with.

That particular error means that there's an out-of-sync error between your version of typebox and the library's. I did fix it for now, but similar may reoccur in the future. Moving to a peer dependency is on my list but it hasn't been critical yet. PRs gratefully appreciated.

**Comment by eropple** [comment]
Next version (commit 170741b) has typebox moved to a peer dependency.
